apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: static-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Raisal-A/helm-charts-testing.git
        revision: master
        files:
          - path: "nahdi-mw/uat-values.yaml"  # Updated path
  template:
    metadata:
      name: nahdi-test
      annotations:
        alb.ingress.kubernetes.io/group.name: 'nahdi-dev'
    spec:
      project: nahdi-sso
      source:
        repoURL: https://github.com/Raisal-A/helm-charts-testing.git
        targetRevision: master
        path: nahdi-mw
        helm:
          valueFiles:
            - uat-values.yaml  # Update the path if necessary
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
